### ISSUE TITLE
Prod lauch checklist

### ISSUE THREAD

**Issue by abose** [phcode-dev/phoenix-desktop#232]
All Prod verifications should be done in windows, linux and mac. tick each platform tests for each checklist item below

## Desktop App

- [x] Run full test suite: https://github.com/phcode-dev/phoenix-desktop/pull/326
- [x] Prod app beta name suffix
- [x] prod app update works
- [x] Verify bugsnag performance metrics in prod. Related: https://github.com/phcode-dev/phoenix/issues/1247
- [x] Health report is prod google analytics. related: https://github.com/phcode-dev/phoenix/issues/1203
- [x] kubuntu not working? and installer test
- [x] Verify `open with Phoenix` is working in Mac finder, windows explorer and linux file manager
- [x] Verify `Open folder` with phoenix in windows and linux from os file explorer. feature not supported in mac.
- [x] When using `open with`, the new project window should not come. 1 window case, multiple window case
- [ ] Verify phoenix can be launched from terminal in linux with `phcode` command. Not available in mac and windows right now.
- [x] should open links in default browser in all os.

## Website
- [x] https://github.com/phcode-dev/phoenix/issues/1202
- [x] https://github.com/phcode-dev/phoenix-desktop/issues/214
